### ISSUE TITLE
Bug in HealthCheckOperation.ExecuteHealthCheckAsync?

### ISSUE THREAD

**Issue by leeprtc** [Azure-Samples/service-fabric-watchdog-service#1]
In ExecuteHealthCheckAsync, a HTTP request is sent. Afterwards, the code checks the result of the request to determine the HealthState. In the check for the result of the request to determine the HealthState, the code checks against hc.ResultCode. Shouldn't the HealthState be determine from the result of the HTTP request?

`
406                 // Make the request to the service being tested. 
407                 Stopwatch sw = Stopwatch.StartNew(); 
408                 HttpResponseMessage response = await this._http.SendAsync(request, HttpCompletionOption.ResponseContentRead, this._token); 
409                 sw.Stop(); 
410 
 
411                 // Evaluate the result of the request. If specific codes were provided, check each of the code arrays to find the result code. 
412                 if ((null != hc.WarningStatusCodes) && (hc.WarningStatusCodes.Contains((int) hc.ResultCode))) 
413                 { 
414                     hs = HealthState.Warning; 
415                     success = false; 
416                 } 
417                 else if ((null != hc.ErrorStatusCodes) && (hc.ErrorStatusCodes.Contains((int) hc.ResultCode))) 
418                 { 
419                     hs = HealthState.Error; 
420                     success = false; 
421                 } 
422                 else if (false == hc.ResultCode.IsSuccessCode()) 
423                 { 
424                     hs = HealthState.Error; 
425                     success = false; 
426                 } 
`

Maybe, there is there a missing step before the evaluation of the result of the request (before line 412)? Seeing all the checks to determine the HealthState is against hc.ResultCode, maybe the code is missing an assignment to hc.ResultCode, i.e. "hc.ResultCode = response.StatusCode".

**Comment by toddabel** [comment]
This is by design. You are allowed to add your status codes as warnings or errors, e.g. you could make a 204 HttpStatusCode result be a warning or an error by specifying it as part of the Warning/ErrorStatusCodes. If no custom status codes are specified, then the default is if the result is a successCode success will be returns, otherwise an error.

**Comment by leeprtc** [comment]
But what you described is not how the code works since the checks against the specified Warning/ErrorStatusCodes are against hc.ResultCode and not against the result of the HTTP request. When you report the health result, the reported health state does not reflect the result of the HTTP request.

**Comment by toddabel** [comment]
You are correct the hc.RequestCode should be changed to response.StatusCode for all three references. I don't change the hc.ResultCode until the last line of the method.
