### ISSUE TITLE
Use a better Http Communcitations Client for the watchdog service

### ISSUE THREAD

**Issue by FunksMaName** [Azure-Samples/service-fabric-watchdog-service#3]
The health check operation to self registered service currently uses a vanilla HttpClient that has no retry policy for Transient and Non-Transient exceptions which occur when services within the cluster are re-provisioned. 

This makes the current source code as it currently stands, not fit for production use. Would it be possible to utilise a suitable HTTP Communication client, similar to what is in the WordCount sample application so that the underlying client handles a retry of the service partition resolver when the endpoint is stale? 

 [Further reading here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication)

[HttpCommunicationClientFactory](https://github.com/c3-ls/ServiceFabric-Http/blob/master/src/C3.ServiceFabric.HttpCommunication/HttpCommunicationClientFactory.cs)

**Comment by dkkapur** [comment]
Fair - the purpose of this sample is mainly meant to help you write your own watchdog so I definitely think it would be worth recommending this. Perhaps in the readme to begin with, and we can consider upgrading the sample as well. Lifting this into production use is not a great idea, and not something I'd like to encourage considering scenarios vary significantly for users.

**Comment by FunksMaName** [comment]
Agreed, so, we've gone live with a highly customized version of the repo and it has held up well so far. A few of the major things we changed were 

- Retry logic for stale endpoints
- Improved error handling withing the watchdog itself and eventflow integration 
- Using the reverse proxy endpoint for service health participation registration was not an option for us, our infrastructure guys would not allow it, hence we changed that a little bit. 
- Fluent library for participating services to register themselves with the watchdog and support for reasonable default configurations. 

I will be looking to tidy it up sometime soon and make it available on here. Great ropo to base the work on. 

Thanks
